// Generated by Grafana k6 Studio (1.9.0) on 2026-01-07T04:41:20.661Z

import { browser } from "k6/browser";

export const options = {
  scenarios: {
    default: {
      executor: "shared-iterations",
      options: { browser: { type: "chromium" } },
    },
  },
};

export default async function () {
  const page = await browser.newPage();

  await page.goto("http://localhost:5000/login");

  await page.locator('[name="username"]').fill("admin");

  await page.locator('[name="password"]').fill("admin123");

  await Promise.all([
    page.waitForNavigation(),
    page.getByRole("button", { name: "Login", exact: true }).click(),
  ]);

  await page
    .getByRole("heading", { name: "Login Successful!", exact: true })
    .click();

  await page.locator("html").click();
}

